# Generated by Django 2.2.2 on 2019-07-15 15:56

from django.db import migrations


class Migration(migrations.Migration):

	dependencies = [("djstripe", "0005_auto_20190710_1023")]

	operations = [
		migrations.AlterField(
			model_name="subscription",
			name="status",
			field=djstripe.fields.StripeEnumField(
				enum=djstripe.enums.SubscriptionStatus, help_text="The status of this subscription.", max_length=18
			),
		),
	]
